spring.application.name=transactions
server.port=8081

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


springdoc.swagger-ui.with-credentials=true
swagger.jwt.header=Authorization
swagger.jwt.prefix=Bearer

GATEWAY_HOST=gateway-service:5050

token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3NjE1MDg4NTMsImV4cCI6MTc5MzA0NDg1MywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsInJvbGUiOiJTRVJWSUNFIiwiU3VybmFtZSI6IlJvY2tldCIsIkVtYWlsIjoianJvY2tldEBleGFtcGxlLmNvbSIsIlJvbGUiOlsiTWFuYWdlciIsIlByb2plY3QgQWRtaW5pc3RyYXRvciJdfQ.wMGQAXpWPJBDpSVrFoNc5c86i7yS1iswkuKE3Fff3ULnx7jI_3hhpHOomn0RWey0schNfKNQd_cMs00xPFVdSw


spring.data.redis.database=0
spring.cache.redis.time-to-live=7d
spring.cache.redis.cache-null-values=false
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.client-type=jedis


spring.kafka.bootstrap-servers=${KAFKA_HOST}:${KAFKA_PORT}

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Pour JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Optional: auto offset reset
spring.kafka.consumer.auto-offset-reset=earliest
spring.jmx.enabled=false

logging.level.org.hibernate=WARN

logging.level.root=WARN

# Niveau par package ou classe
logging.level.ca.log430.transactions=INFO
logging.level.org.springframework.kafka=WARN
logging.level.org.hibernate.SQL=WARN
